name: CI

on:
  pull_request:
    branches: [prod]

permissions:
  contents: read
  pull-requests: write

jobs:
  # Combine lint and test jobs to reduce duplicate setup
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Shallow clone for faster checkout

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run pull-request checks
        run: |
          npm run pr

      - name: "Report Coverage"
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2

    # Add timeout to prevent hanging jobs
    timeout-minutes: 10

    # Add concurrency to cancel redundant workflow runs
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
