name: Prompt Submission

on:
  pull_request:
    paths:
      - "content/prompts/**/*.md"
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  validate-prompts:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
      any-changed: ${{ steps.changed-files.outputs.any_changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Get changed markdown files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            content/prompts/**/*.md

      - name: Validate changed prompts
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Changed markdown files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"

          exit_code=0
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Validating: $file"
            if ! npm run validate:prompts "$file"; then
              exit_code=1
            fi
            echo "---"
          done

          exit $exit_code

      - name: Validate all prompts (fallback)
        if: steps.changed-files.outputs.any_changed == 'false'
        run: |
          echo "No markdown files changed, running full validation as safety check"
          npm run validate:prompts

      - name: Comment on validation failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const commentFailure = require('./.github/scripts/comment-validation-failure.js');
            await commentFailure({ github, context });

  build:
    runs-on: ubuntu-latest
    needs: validate-prompts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Build prompt index
        run: npm run build:index

      - name: Test full build process
        run: |
          npx ampx generate outputs --branch main --app-id ${{ secrets.AMPLIFY_APP_ID }}
          npm run build

      - name: Comment on build failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const commentFailure = require('./.github/scripts/comment-validation-failure.js');
            await commentFailure({ github, context });

  approval:
    runs-on: ubuntu-latest
    needs: [validate-prompts, build]
    if: needs.validate-prompts.outputs.any-changed == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check approval criteria
        id: approval-check
        uses: actions/github-script@v7
        with:
          script: |
            const checkCriteria = require('./.github/scripts/check-approval-criteria.js');
            return await checkCriteria({ github, context });

      - name: Auto-approve PR
        if: fromJSON(steps.approval-check.outputs.result).needsManualReview == false
        uses: actions/github-script@v7
        with:
          script: |
            const autoApprove = require('./.github/scripts/auto-approve.js');
            await autoApprove({ 
              github, 
              context, 
              changedFiles: '${{ needs.validate-prompts.outputs.changed-files }}' 
            });

      - name: Request manual review
        if: fromJSON(steps.approval-check.outputs.result).needsManualReview == true
        uses: actions/github-script@v7
        with:
          script: |
            const requestReview = require('./.github/scripts/request-manual-review.js');
            const criteria = JSON.parse('${{ steps.approval-check.outputs.result }}');
            await requestReview({ 
              github, 
              context, 
              criteria,
              changedFiles: '${{ needs.validate-prompts.outputs.changed-files }}' 
            });
